services:
  backend:
    image: sp
    build:
      context: ./backend
      dockerfile: nonroot-multistage.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d0ne3b1r0fns738ua1f0-a.oregon-postgres.render.com:5432/database_1_kxko
      - SPRING_DATASOURCE_USERNAME=batman
      - SPRING_DATASOURCE_PASSWORD=WYAbOw0HJYjHCZHXjs7VSxkS2Hz3llwZ
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3

  frontend:
    image: front
    build: 
      context: ./frontend
      dockerfile: node.Dockerfile
      args:
        VITE_BACKEND: http://backend:8080
    environment:
      - VITE_BACKEND=http://backend:8080
    ports:
      - "7000:7000"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  dslabdb:
