services:
  backend:
    image: ghcr.io/orestis-apostolou/crowdfunding-ansible:backend-0a052d7 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d1ba8deuk2gs739hpvmg-a.oregon-postgres.render.com:5432/gotham_c6ry
      SPRING_DATASOURCE_USERNAME: batman
      SPRING_DATASOURCE_PASSWORD: adwMC1t49HbHiMeFfEOdJHRWlAAqzcIF
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3

  frontend:
    image: ghcr.io/orestis-apostolou/crowdfunding-ansible:frontend-352b8b7
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
