version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: nonroot-multistage.Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0ne3b1r0fns738ua1f0-a.oregon-postgres.render.com:5432/database_1_kxko
      SPRING_DATASOURCE_USERNAME: batman
      SPRING_DATASOURCE_PASSWORD: WYAbOw0HJYjHCZHXjs7VSxkS2Hz3llwZ
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: node.Dockerfile
    command: ["node", "serverInit.js"]

  nginx:
    image: nginx:stable-alpine
    ports:
      - "7000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
