---
  - name: Frontend process
    hosts: frontend
    
    tasks:
      - name: clone git repository
        git:
          repo: 'https://github.com/Orestis-Apostolou/crowdfunding-ansible.git'
          dest: "{{ clonedir }}"
          version: main
          force: yes

      - name: install docker-compose
        apt:
          name: 
            - docker-compose
            - docker.io
          state: present
          update_cache: yes
        become: yes

      # - name: render nginx config from j2 template
      #   template:
      #     src: ../files/nginx.http.j2
      #     dest: "{{ clonedir }}"
      #   become: yes

      - name: ensure docker service is running
        service:
          name: docker
          state: started
          enabled: yes
        become: yes

      - name: run docker compose up 
        command: docker-compose up -d
        args:
          chdir: "{{ clonedir }}"
        become: yes
