---
  - name: Frontend process
    hosts: frontend

    vars:
      app_dir: "{{ ansible_env.HOME }}/frontend"
    
    tasks:
      - name: clone git repository
        git:
          repo: 'https://github.com/Orestis-Apostolou/crowdfunding-ansible.git'
          dest: "{{ ansible_env.HOME }}/src"
          version: main
          force: yes

      - name: remove frontend folder from vm root if it exists
        file:
          path: "{{ app_dir }}"
          state: absent

      - name: copy frontend folder on repo root to ansible vm root
        command: mv {{ ansible_env.HOME }}/src/frontend {{ app_dir }}

      - name: remove the rest of the repository
        file:
          path: "{{ ansible_env.HOME }}/src"
          state: absent

      - name: Install Node.js and npm
        ansible.builtin.apt:
          name:
            - nodejs
            - npm
          state: present
          update_cache: yes
        become: yes

      - name: Running `npm init -y`
        ansible.builtin.command: npm init -y
        args:
          chdir: "{{ app_dir }}"
          creates: "{{ app_dir }}/package.json"

      - name: Running npm install
        community.general.npm:
          path: "{{ app_dir }}"

      - name: "Install forever (to run Node.js app)."
        npm:
          name: forever
          global: yes
          state: present
        become: yes

      # - name: Show the app_dir path
      #   debug:
      #     var: app_dir

      - name: "Check list of Node.js apps running."
        command: forever list
        register: forever_list
        changed_when: false

      - name: "Start example Node.js app if not already running."
        command: "forever start {{ app_dir }}/serverInit.js"
        when: app_dir + '/serverInit.js' not in forever_list.stdout

      # - name: "Stop the app server with forever"
      #   command: "forever stop {{ app_dir }}/serverInit.js"

      #source: https://stackoverflow.com/questions/20919222/ansible-hangs-when-starting-node-js-server



