---
  - name: Frontend process
    hosts: frontend
    become: yes

    vars:
      app_dir: "{{ ansible_env.HOME }}/frontend"
    
    tasks:
      - name: clone git repository
        git:
          repo: 'https://github.com/Orestis-Apostolou/crowdfunding-ansible.git'
          dest: "{{ ansible_env.HOME }}/src"
          version: main
          force: yes

      - name: remove frontend folder from vm root if it exists
        file:
          path: "{{ app_dir }}"
          state: absent

      - name: copy frontend folder on repo root to ansible vm root
        command: mv {{ ansible_env.HOME }}/src/frontend {{ ansible_env.HOME }}/frontend

      - name: remove the rest of the repository
        file:
          path: "{{ ansible_env.HOME }}/src"
          state: absent

      - name: Install Node.js and npm
        ansible.builtin.apt:
          name:
            - nodejs
            - npm
          state: present
          update_cache: yes

      - name: Running `npm init -y`
        ansible.builtin.command: npm init -y
        args:
          chdir: "{{ app_dir }}"
          creates: "{{ app_dir }}/package.json"

      - name: Running npm install
        community.general.npm:
          path: "{{ app_dir }}"

      - name: Running node script (In a different process)
        ansible.builtin.command:
          cmd: nohup node serverInit.js > /dev/null 2>&1 &
          chdir: "{{ app_dir }}"

