---
  - name: Frontend process
    hosts: frontend
    
    tasks:
      - name: clone git repository
        git:
          repo: 'https://github.com/Orestis-Apostolou/crowdfunding-ansible.git'
          dest: "{{ clonedir }}"
          version: main
          force: yes

      - name: remove frontend folder from vm root if it exists
        file:
          path: "{{ appdir }}/frontend"
          state: absent
        become: yes

      - name: install nginx
        apt:
          name: nginx
          update_cache: yes
        become: yes

      - name: copy frontend folder on clone directory to nginx default
        command: mv {{ clonedir }}/frontend {{ appdir }}
        become: yes

      - name: copy nginx config
        template:
          src: ../files/nginx.http.j2
          dest: "/etc/nginx/sites-available/spring"
        become: yes
      
      - name: enable site in nginx
        file:
          src: "/etc/nginx/sites-available/spring"
          dest: "/etc/nginx/sites-enabled/spring"
          state: link
        become: yes
        notify: restart nginx

      - name: disable nginx default site
        file:
          path: /etc/nginx/sites-enabled/default
          state: absent
        become: yes
        notify: restart nginx

      - name: remove the rest of the repository
        file:
          path: "{{ clonedir }}"
          state: absent

    handlers:
      - name: restart nginx
        service:
          name: nginx
          state: restarted
        become: yes
