---
  - name: install spring boot application
    hosts: backend

    tasks:
      - name: install java version 21
        apt:
          name: openjdk-21-jdk
          state: present
          update-cache: yes
        become: yes

      - name: clone git repository
        git:
          repo: 'https://github.com/Orestis-Apostolou/crowdfunding-ansible.git'
          dest: "{{ clonedir }}"
          version: main
          force: yes

      - name: remove backend folder from vm root if it exists
        file:
          path: "{{ appdir }}"
          state: absent

      - name: copy backend folder on repo root to ansible vm root
        command: mv {{ clonedir }}/backend {{ appdir }}

      - name: remove the rest of the repository
        file:
          path: "{{ clonedir }}"
          state: absent

      - name: add database connection details to application.properties
        lineinfile:
          dest: "{{ appdir }}/src/main/resources/application.properties"
          regex: "^{{ item.key }}="
          line: "{{ item.key }}={{item.value}}"
          state: present
        with_items:
          - "{{ app.env | dict2items}}"

      - name: build maven project
        command: "./mvnw package -Dmaven.test.skip"
        args:
          chdir: "{{ appdir }}"
