  appdir: "{{ ansible_user_dir }}/backend"  
  appuser: "{{ ansible_user_id }}"
  appgroup: "{{ ansible_user_gid }}"

  app:
    env:
      server.port: "8080"
      spring.datasource.username: "batman"
      spring.datasource.password: "WYAbOw0HJYjHCZHXjs7VSxkS2Hz3llwZ"
      spring.datasource.url: "jdbc:postgresql://dpg-d0ne3b1r0fns738ua1f0-a.oregon-postgres.render.com:5432/database_1_kxko" 
